### PR TITLE
Make the plugin compatible with hashicorp-vault-plugin 3.0.0 and add optional engineVersion usage

### PR DESCRIPTION
**Pull request by alexandruivan**

### CODE REVIEW

**Comment by alexandruivan** [comment]
@philmadden83 Any chance to review these changes and maybe release the plugin to fix the compatibility with the latest hashicorp-vault-plugin?

**Comment by philmadden83** [comment]
@alexandruivan absolutely. Your PR has similar changes to [this pr](https://github.com/jenkinsci/hashicorp-vault-pipeline-plugin/pull/14#partial-pull-merging) so I will be picking the best from each and merging both. It probably means one will be closed.

**Comment by alexandruivan** [comment]
@philmadden83 I don't mind as long as the plugin works :)

**Comment by pappnase99** [comment]
After running into both plugins becoming incompatible, this change would be much appreciated.

**Comment by philmadden83** [comment]
@pappnase99 @alexandruivan I'll make my best effort to get this released for you today. Either this branch or the other with a similar fix.

**Comment by philmadden83** [comment]
@alexandruivan on closer inspection the two PRs were solving subtly different things - as a result, after merging the first you now have conflicts. Can you please address them and I'll cut a release once done.

**Comment by jgracin** [comment]
Hi guys! Any progress on resolving this one? I think my declarative pipeline breaks because of this. Thanks!

**Comment by philmadden83** [comment]
@alexandruivan @jgracin ill see if I can resolve these conflicts myself and get this merged and released.

**Comment by JCEmmons** [comment]
I'm running into this problem, too, and it seems others are as well.  How can we get this over the finish line???

**Comment by raivil** [comment]
Any updates on this issue?

**Comment by philmadden83** [comment]
@raivil @JCEmmons sorry for the delay/frustration. I'll get on this and get it released.

**Comment by kunickiaj** [comment]
Def need to get 3.x plugin compatibility merged please... if there's anything I can do to help speed this along happy to help.

**Comment by pappnase99** [comment]
So is this thing dead?

**Comment by philmadden83** [comment]
@pappnase99 we have conflicts which need resolving. I messaged @alexandruivan here https://github.com/jenkinsci/hashicorp-vault-pipeline-plugin/pull/15#issuecomment-581459396

**Comment by mifitous** [comment]
Hi guys! Any progress on resolving this one? I think my declarative pipeline breaks because of this. Thanks!

@philmadden83 @alexandruivan

**Comment by philmadden83** [comment]
Closing due to changes being merged as part of https://github.com/jenkinsci/hashicorp-vault-pipeline-plugin/pull/18.

This is now in the 1.4 release of the plugin.

**Pull request closed without merging**
